apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: injection-cluster-defaults
  namespace: testing
spec:
  enabled: true
  type: dummy
  selector:
    labels:
      - name: app
        value: injection-cluster-defaults
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: injection-cluster-defaults
  namespace: testing
  labels:
    app: injection-cluster-defaults
spec:
  replicas: 1
  selector:
    matchLabels:
      app: injection-cluster-defaults
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: injection-cluster-defaults
    spec:
      containers:
        - image: k8s.gcr.io/pause:3.3
          name: pause
