resources:
  - cluster-agent-configuration.yaml
  - cluster-agent-connection-secret.yaml
  - cluster-agent-connection.yaml
  - cluster-agent-injector.yaml
  - injection-cluster-defaults.yaml
  - injection-cluster-injector.yaml
  - injection-namespacelabel.yaml
